[project]
name = "moltbook-study"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]
